name: k2d-ci

on:
  push:
    branches:
    - "develop"
    - "!release/*"
  pull_request:
    branches:
    - "develop"
    - "release/*"
    - "feat/*"
    - "fix/*"
    - "refactor/*"

env:
  DOCKER_HUB_CI_REPOSITORY: portainerci
  CONTINAER_IMAGE_TAG: pr${{ github.event.pull_request.labels.name }}

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
    - name: "[preparation] checkout the current branch"
      uses: actions/checkout@v3.5.3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: "[preparation] extract the branch name"
      shell: bash
      run: |
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: "[preparation] set up golang 1.20.4"
      uses: actions/setup-go@v4.0.1
      with:
        go-version: "1.20.4"
        cache-dependency-path: ./api/go.sum
    - name: "[preparation] set up qemu"
      uses: docker/setup-qemu-action@v2
    - name: "[preparation] set up docker context for buildx"
      run: docker context create builders
    - name: "[preparation] set up docker buildx"
      uses: docker/setup-buildx-action@v2
      with:
        endpoint: builders
    - name: "[preparation] docker login"
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: "[execution] build k2d and build docker images"
      env:
        if: github.event.pull_request.labels.name == ''
        CONTAINER_IMAGE_TAG: ${{ steps.extract_branch.outputs.branch }}
      run: |     
        make image-multiarch REPOSITORY=${DOCKER_HUB_CI_REPOSITORY} VERSION=${CONTAINER_IMAGE_TAG}